# Managed by Hydra

defaults:
  - base

log:
  WandbLogger:
    project: PointGroup
    name: ${model.model.experiment_name}
  TensorBoardLogger:
    name: PointGroup

trainer:
  max_epochs: 496

optimizer:
    lr: 0.002

lr_decay:
  decay_start_epoch: 250
  decay_stop_epoch: 496

model:
  module: PointGroup
  experiment_name: run_1

  m: 16 # 16 or 32
  blocks: [1, 2, 3, 4, 5, 6, 7]
  cluster_blocks: [1, 2]
  block_reps: 2

  use_coord: True
  use_color: True
  use_multiview: False
  use_normal: False

  fg_thresh: 0.75
  bg_thresh: 0.25

  score_scale: 50  # the minimal voxel size is 2cm
  score_fullscale: 14

  freeze_backbone: False
  prepare_epochs: 128

  loss_weight: [1, 1, 1, 1, 1, 1]

  cluster:
    # point grouping
    cluster_radius: 0.03
    cluster_meanActive: 50
    cluster_shift_meanActive: 300
    cluster_npoint_thre: 50

  test:
    TEST_NMS_THRESH: 0.3
    TEST_SCORE_THRESH: 0.09
    TEST_NPOINT_THRESH: 100
